create table tbl_game (id int8 generated by default as identity, plataform int4, title varchar(255), genre_id int8, primary key (id));
create table tbl_genre (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tbl_record (id int8 generated by default as identity, age int4, moment timestamp, name varchar(255), game_id int8, primary key (id));
alter table if exists tbl_game add constraint FKd1fjdqewid47j770t8cpr9f2g foreign key (genre_id) references tbl_genre;
alter table if exists tbl_record add constraint FKqjnvi1x32r0vjcj9m869ad5jk foreign key (game_id) references tbl_game;
INSERT INTO tbl_genre (name) VALUES ('Shooter');
INSERT INTO tbl_genre (name) VALUES ('MOBA');
INSERT INTO tbl_genre (name) VALUES ('RPG');
INSERT INTO tbl_genre (name) VALUES ('Battle Royale');
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('The Witcher 3', 2, 3);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('League of Legends', 0, 2);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('CS GO', 0, 1);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Cyberpunk 2077', 0, 3);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Cyberpunk 2077', 2, 3);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('God of War', 0, 3);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('God of War', 1, 3);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Overwatch', 0, 1);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Valorant', 0, 1);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Fall Guys', 0, 4);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Fall Guys', 1, 4);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Fortnite', 0, 4);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Dragon Age Inquisition', 2, 3);
INSERT INTO tbl_game (title, plataform, genre_id) VALUES ('Dragon Age Inquisition', 1, 3);
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (3, 'Tulio', 44, TIMESTAMP WITH TIME ZONE '2020-07-21T20:59:19Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Tito', 23, TIMESTAMP WITH TIME ZONE '2020-06-16T07:22:12Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (8, 'Bob', 46, TIMESTAMP WITH TIME ZONE '2020-06-04T12:43:47Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (9, 'Manasses', 43, TIMESTAMP WITH TIME ZONE '2020-05-29T00:39:12Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Marcos', 30, TIMESTAMP WITH TIME ZONE '2020-05-07T18:58:45Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Marcos', 26, TIMESTAMP WITH TIME ZONE '2020-05-20T15:12:10Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Jessica', 35, TIMESTAMP WITH TIME ZONE '2020-06-23T00:38:49Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Marcela', 23, TIMESTAMP WITH TIME ZONE '2020-05-01T05:40:58Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Tulio', 37, TIMESTAMP WITH TIME ZONE '2020-06-26T00:51:12Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Tony', 37, TIMESTAMP WITH TIME ZONE '2020-07-28T05:46:23Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Monica', 35, TIMESTAMP WITH TIME ZONE '2020-06-28T10:49:12Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Ana', 20, TIMESTAMP WITH TIME ZONE '2020-05-25T11:29:38Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (2, 'Bob', 37, TIMESTAMP WITH TIME ZONE '2020-06-05T05:03:03Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (3, 'Erico', 43, TIMESTAMP WITH TIME ZONE '2020-05-21T03:30:32Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Maria', 20, TIMESTAMP WITH TIME ZONE '2020-07-23T16:49:02Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Tony', 18, TIMESTAMP WITH TIME ZONE '2020-05-15T02:24:46Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Filipe', 24, TIMESTAMP WITH TIME ZONE '2020-05-14T08:26:00Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (2, 'Marcela', 27, TIMESTAMP WITH TIME ZONE '2020-07-25T13:11:09Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Monica', 39, TIMESTAMP WITH TIME ZONE '2020-06-03T04:28:58Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Monica', 34, TIMESTAMP WITH TIME ZONE '2020-07-12T20:12:21Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Meire', 39, TIMESTAMP WITH TIME ZONE '2020-05-12T14:57:23Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Marina', 25, TIMESTAMP WITH TIME ZONE '2020-06-23T12:17:23Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Tito', 20, TIMESTAMP WITH TIME ZONE '2020-05-20T15:24:43Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (13, 'Ana', 36, TIMESTAMP WITH TIME ZONE '2020-07-01T16:51:09Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Jessica', 25, TIMESTAMP WITH TIME ZONE '2020-06-03T13:08:05Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Aline', 41, TIMESTAMP WITH TIME ZONE '2020-06-12T23:50:42Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Maria', 35, TIMESTAMP WITH TIME ZONE '2020-05-23T15:33:18Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Cesar', 25, TIMESTAMP WITH TIME ZONE '2020-07-02T19:06:52Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (14, 'Bob', 38, TIMESTAMP WITH TIME ZONE '2020-06-26T13:49:49Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Alex', 30, TIMESTAMP WITH TIME ZONE '2020-05-26T00:13:35Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Cesar', 30, TIMESTAMP WITH TIME ZONE '2020-05-04T22:08:03Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Tulio', 46, TIMESTAMP WITH TIME ZONE '2020-07-21T08:58:17Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Cesar', 44, TIMESTAMP WITH TIME ZONE '2020-06-02T20:51:22Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Marcela', 27, TIMESTAMP WITH TIME ZONE '2020-07-13T23:17:38Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Bob', 39, TIMESTAMP WITH TIME ZONE '2020-06-28T19:16:40Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (2, 'Erico', 40, TIMESTAMP WITH TIME ZONE '2020-07-29T02:41:47Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Marcos', 47, TIMESTAMP WITH TIME ZONE '2020-07-15T23:10:50Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (8, 'Tito', 41, TIMESTAMP WITH TIME ZONE '2020-06-27T20:03:12Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Francisco', 41, TIMESTAMP WITH TIME ZONE '2020-06-27T22:24:43Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Tony', 21, TIMESTAMP WITH TIME ZONE '2020-05-11T19:08:56Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Erico', 32, TIMESTAMP WITH TIME ZONE '2020-07-17T12:50:52Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Filipe', 22, TIMESTAMP WITH TIME ZONE '2020-07-07T18:33:37Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Tiago', 39, TIMESTAMP WITH TIME ZONE '2020-07-06T22:15:07Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Filipe', 32, TIMESTAMP WITH TIME ZONE '2020-06-06T17:40:06Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Carolina', 20, TIMESTAMP WITH TIME ZONE '2020-07-11T18:25:34Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Manasses', 45, TIMESTAMP WITH TIME ZONE '2020-06-25T10:03:38Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Maria', 31, TIMESTAMP WITH TIME ZONE '2020-06-24T19:13:42Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Marcela', 41, TIMESTAMP WITH TIME ZONE '2020-07-14T11:35:40Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Marina', 27, TIMESTAMP WITH TIME ZONE '2020-07-08T11:32:31Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Carolina', 39, TIMESTAMP WITH TIME ZONE '2020-07-07T06:17:55Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Alex', 29, TIMESTAMP WITH TIME ZONE '2020-05-07T16:55:40Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Meire', 26, TIMESTAMP WITH TIME ZONE '2020-06-21T22:35:13Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Silas', 28, TIMESTAMP WITH TIME ZONE '2020-06-21T07:55:41Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Meire', 27, TIMESTAMP WITH TIME ZONE '2020-06-29T12:36:02Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Cesar', 19, TIMESTAMP WITH TIME ZONE '2020-06-05T23:35:06Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (14, 'Meire', 21, TIMESTAMP WITH TIME ZONE '2020-06-13T00:16:11Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Carolina', 35, TIMESTAMP WITH TIME ZONE '2020-06-21T20:27:18Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (8, 'Marcos', 33, TIMESTAMP WITH TIME ZONE '2020-06-10T09:41:17Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Francisco', 22, TIMESTAMP WITH TIME ZONE '2020-07-17T21:53:18Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (13, 'Francisco', 45, TIMESTAMP WITH TIME ZONE '2020-05-09T16:31:29Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Tito', 29, TIMESTAMP WITH TIME ZONE '2020-07-19T19:39:54Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Tiago', 37, TIMESTAMP WITH TIME ZONE '2020-05-05T16:23:54Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (14, 'Tulio', 35, TIMESTAMP WITH TIME ZONE '2020-06-03T06:06:01Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (2, 'Meire', 25, TIMESTAMP WITH TIME ZONE '2020-07-19T02:02:32Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Francisco', 44, TIMESTAMP WITH TIME ZONE '2020-07-24T03:32:22Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Francisco', 23, TIMESTAMP WITH TIME ZONE '2020-05-18T16:45:37Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (9, 'Ana', 26, TIMESTAMP WITH TIME ZONE '2020-07-07T22:11:51Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Aline', 30, TIMESTAMP WITH TIME ZONE '2020-07-25T12:18:48Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Erico', 21, TIMESTAMP WITH TIME ZONE '2020-05-23T11:24:09Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Marina', 42, TIMESTAMP WITH TIME ZONE '2020-07-04T10:16:40Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Marina', 32, TIMESTAMP WITH TIME ZONE '2020-06-14T13:25:11Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Carlos', 43, TIMESTAMP WITH TIME ZONE '2020-05-29T19:52:07Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Tiago', 34, TIMESTAMP WITH TIME ZONE '2020-07-24T08:36:19Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (9, 'Aline', 46, TIMESTAMP WITH TIME ZONE '2020-07-20T05:32:53Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Manasses', 18, TIMESTAMP WITH TIME ZONE '2020-06-04T11:43:05Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Rita', 36, TIMESTAMP WITH TIME ZONE '2020-05-08T18:06:04Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Manasses', 22, TIMESTAMP WITH TIME ZONE '2020-07-15T14:19:44Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Tiago', 21, TIMESTAMP WITH TIME ZONE '2020-05-15T16:58:55Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Maria', 26, TIMESTAMP WITH TIME ZONE '2020-06-04T10:20:57Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Marcos', 30, TIMESTAMP WITH TIME ZONE '2020-06-10T06:55:09Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Bob', 45, TIMESTAMP WITH TIME ZONE '2020-07-08T20:00:48Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (8, 'Marina', 41, TIMESTAMP WITH TIME ZONE '2020-06-16T13:14:52Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Maria', 33, TIMESTAMP WITH TIME ZONE '2020-06-08T13:26:00Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (8, 'Aline', 41, TIMESTAMP WITH TIME ZONE '2020-05-19T01:56:48Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Maria', 20, TIMESTAMP WITH TIME ZONE '2020-07-28T23:53:21Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (2, 'Aline', 39, TIMESTAMP WITH TIME ZONE '2020-06-15T23:42:27Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (3, 'Tulio', 26, TIMESTAMP WITH TIME ZONE '2020-06-02T16:05:39Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (13, 'Rita', 34, TIMESTAMP WITH TIME ZONE '2020-07-30T06:33:00Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (14, 'Cesar', 41, TIMESTAMP WITH TIME ZONE '2020-07-11T14:05:22Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (9, 'Carlos', 22, TIMESTAMP WITH TIME ZONE '2020-05-29T01:54:35Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Carlos', 27, TIMESTAMP WITH TIME ZONE '2020-06-10T19:30:33Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Tulio', 32, TIMESTAMP WITH TIME ZONE '2020-07-02T22:32:56Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (9, 'Silas', 43, TIMESTAMP WITH TIME ZONE '2020-07-10T11:30:09Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Meire', 24, TIMESTAMP WITH TIME ZONE '2020-06-21T08:29:45Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Meire', 28, TIMESTAMP WITH TIME ZONE '2020-06-30T10:27:21Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Tony', 29, TIMESTAMP WITH TIME ZONE '2020-07-06T10:09:46Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Maria', 24, TIMESTAMP WITH TIME ZONE '2020-06-17T04:34:20Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (8, 'Carlos', 46, TIMESTAMP WITH TIME ZONE '2020-07-05T13:40:20Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (13, 'Ana', 45, TIMESTAMP WITH TIME ZONE '2020-05-07T03:56:32Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Filipe', 43, TIMESTAMP WITH TIME ZONE '2020-06-10T17:39:52Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Tulio', 21, TIMESTAMP WITH TIME ZONE '2020-05-22T23:35:31Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (8, 'Monica', 42, TIMESTAMP WITH TIME ZONE '2020-06-03T22:37:55Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Erico', 24, TIMESTAMP WITH TIME ZONE '2020-07-17T11:50:22Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (3, 'Meire', 30, TIMESTAMP WITH TIME ZONE '2020-05-15T03:22:50Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (2, 'Francisco', 20, TIMESTAMP WITH TIME ZONE '2020-07-09T13:22:12Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Silas', 19, TIMESTAMP WITH TIME ZONE '2020-05-17T08:03:08Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (13, 'Bob', 22, TIMESTAMP WITH TIME ZONE '2020-07-13T09:04:01Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Tulio', 19, TIMESTAMP WITH TIME ZONE '2020-05-28T12:00:37Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Rita', 24, TIMESTAMP WITH TIME ZONE '2020-05-11T02:15:40Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Aline', 20, TIMESTAMP WITH TIME ZONE '2020-05-01T22:43:35Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (3, 'Carolina', 18, TIMESTAMP WITH TIME ZONE '2020-06-22T02:48:39Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Tony', 28, TIMESTAMP WITH TIME ZONE '2020-06-09T21:45:20Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Maria', 33, TIMESTAMP WITH TIME ZONE '2020-05-30T05:59:56Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (9, 'Ana', 42, TIMESTAMP WITH TIME ZONE '2020-07-06T22:57:28Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Monica', 24, TIMESTAMP WITH TIME ZONE '2020-07-16T19:28:31Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Bob', 22, TIMESTAMP WITH TIME ZONE '2020-05-28T04:33:37Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (13, 'Alex', 18, TIMESTAMP WITH TIME ZONE '2020-06-01T19:10:08Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (4, 'Marina', 27, TIMESTAMP WITH TIME ZONE '2020-06-20T07:05:43Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (8, 'Tiago', 36, TIMESTAMP WITH TIME ZONE '2020-05-17T12:10:00Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (2, 'Manasses', 40, TIMESTAMP WITH TIME ZONE '2020-06-05T22:23:12Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Tulio', 43, TIMESTAMP WITH TIME ZONE '2020-05-20T11:40:56Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Marcela', 19, TIMESTAMP WITH TIME ZONE '2020-07-18T16:48:43Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Tony', 27, TIMESTAMP WITH TIME ZONE '2020-07-13T13:08:47Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (13, 'Monica', 47, TIMESTAMP WITH TIME ZONE '2020-07-18T15:02:10Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (14, 'Tony', 35, TIMESTAMP WITH TIME ZONE '2020-05-31T04:52:18Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (13, 'Manasses', 44, TIMESTAMP WITH TIME ZONE '2020-07-24T10:46:01Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Marcela', 42, TIMESTAMP WITH TIME ZONE '2020-07-23T20:08:36Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Meire', 23, TIMESTAMP WITH TIME ZONE '2020-06-06T15:39:10Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Marina', 26, TIMESTAMP WITH TIME ZONE '2020-05-25T12:29:17Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Maria', 25, TIMESTAMP WITH TIME ZONE '2020-05-08T20:34:49Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Francisco', 41, TIMESTAMP WITH TIME ZONE '2020-06-24T07:41:40Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Jessica', 18, TIMESTAMP WITH TIME ZONE '2020-06-04T10:33:15Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Marina', 39, TIMESTAMP WITH TIME ZONE '2020-06-05T08:07:52Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (6, 'Meire', 34, TIMESTAMP WITH TIME ZONE '2020-05-26T18:01:20Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (7, 'Cesar', 40, TIMESTAMP WITH TIME ZONE '2020-05-02T09:57:52Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (11, 'Silas', 34, TIMESTAMP WITH TIME ZONE '2020-07-20T19:47:59Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Aline', 32, TIMESTAMP WITH TIME ZONE '2020-07-11T18:00:15Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (14, 'Marcela', 24, TIMESTAMP WITH TIME ZONE '2020-05-08T20:15:34Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (5, 'Carlos', 32, TIMESTAMP WITH TIME ZONE '2020-07-17T04:35:32Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (10, 'Filipe', 38, TIMESTAMP WITH TIME ZONE '2020-05-20T04:20:48Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (3, 'Tulio', 27, TIMESTAMP WITH TIME ZONE '2020-07-29T22:41:07Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (12, 'Alex', 27, TIMESTAMP WITH TIME ZONE '2020-06-14T21:05:20Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (1, 'Aline', 24, TIMESTAMP WITH TIME ZONE '2020-05-06T21:06:39Z');
INSERT INTO tbl_record (game_id, name, age, moment) VALUES (3, 'Erico', 36, TIMESTAMP WITH TIME ZONE '2020-06-01T14:24:21Z');


postgres://

luxkriswjhtoqc

0717c6551b4c280ee82b1041dc137a30f7019d98f92f94b0c5af044f51d22753

ec2-107-20-153-39.compute-1.amazonaws.com

5432/d4b4f7r94afgks

fetch("https://demo-pesquisa.herokuapp.com/records", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:3000/records",
  "referrerPolicy": "no-referrer-when-downgrade",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});

npx-create-react-app front-web --template=typescript